[features]
seeds = false

[programs.devnet]
whitelisting = "DoXHuZ7cuGeDiLV6AwnoEsMLo1UGZ3AX5Mk7KgEy4UwV"
counter = "3pBmYTFPiUNstae4M2WUAQ6Giydr4nstQ6rnM1TXh8vk"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/jamesw/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
